alias la='ls -a'
alias ll='ls -l'
alias gti=git
alias vom=vim
alias ne='node -e'

alias yarni='rm -rf node_modules yarn.lock package-lock.json; yarn'
alias yarnt='yarn test'
alias npmi='rm -rf node_modules package-lock.json; npm install'

alias rnra='react-native run-android'
alias adbr='adb reverse tcp:8081 tcp:8081'
alias adbl='adb logcat'

alias resource='source ~/.bashrc'

if [ $(uname -s) == "Linux" ]
then
    alias open='xdg-open'
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xsel -b'
fi

ssh-port-forward() {
    local port=$1
    shift
    ssh -qL ${port}:127.0.0.1:${port} $@
}

gitb() {
    for a in $@
    do
        git $a
    done
}

line() {
    if [ $# -eq 2 ]
    then
        sed "$1q;d" "$2"
    else
        sed "$1q;d"
    fi
}

export HISTCONTROL=ignoreboth:erasedups
