alias gti=git
alias la='ls -a'
alias ll='ls -l'
alias ne='node -e'
alias vom=vim

alias npmi='rm -rf node_modules; npm install'
alias yarni='rm -rf node_modules; yarn'
alias yarnt='yarn test'
alias ysr='yarn start --reset-cache'

alias adbd='adb devices'
alias adbl='adb logcat'
alias adbll='adb logcat -T1 | grep "ReactNativeJS\\|System\\."'
alias adbr='adb reverse tcp:8081 tcp:8081'
alias rnra='react-native run-android'
alias rrnra='adb uninstall $(grep package android/app/src/main/AndroidManifest.xml | cut -d\" -f2); rnra'

alias resource='source ~/.bashrc'

case $(uname -s) in
    "Linux")
        alias open='xdg-open'
        alias pbcopy='xclip -selection clipboard'
        alias pbpaste='xsel -b'
        ;;
    "Darwin")
        alias tac='tail -r'
        ;;
esac

ssh-port-forward() {
    local port=$1
    shift
    ssh -qL ${port}:127.0.0.1:${port} $@
}

gitb() {
    for a in $@
    do
        git $a
    done
}

# for when you type `gi tstatus` instead of `git status`
gi() {
    local first=$1
    shift
    git ${first:1} $@
}

line() {
    if [ $# -eq 2 ]
    then
        sed "$1q;d" "$2"
    else
        sed "$1q;d"
    fi
}

export HISTCONTROL=ignoreboth:erasedups
